<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class QuantityWarehouse extends \Application\Entity\QuantityWarehouse implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\QuantityWarehouse' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\QuantityWarehouse' . "\0" . 'quantity', 'createdAt', 'updatedAt', '' . "\0" . 'Application\\Entity\\QuantityWarehouse' . "\0" . 'idProductChecked', '' . "\0" . 'Application\\Entity\\QuantityWarehouse' . "\0" . 'idWarehouses'];
        }

        return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\QuantityWarehouse' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\QuantityWarehouse' . "\0" . 'quantity', 'createdAt', 'updatedAt', '' . "\0" . 'Application\\Entity\\QuantityWarehouse' . "\0" . 'idProductChecked', '' . "\0" . 'Application\\Entity\\QuantityWarehouse' . "\0" . 'idWarehouses'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (QuantityWarehouse $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuantity($quantity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuantity', [$quantity]);

        return parent::setQuantity($quantity);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuantity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuantity', []);

        return parent::getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdProductChecked(\Application\Entity\ProductCheck $idProductChecked = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdProductChecked', [$idProductChecked]);

        return parent::setIdProductChecked($idProductChecked);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdProductChecked()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdProductChecked', []);

        return parent::getIdProductChecked();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdWarehouses(\Application\Entity\Warehouses $idWarehouses = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdWarehouses', [$idWarehouses]);

        return parent::setIdWarehouses($idWarehouses);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdWarehouses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdWarehouses', []);

        return parent::getIdWarehouses();
    }

    /**
     * {@inheritDoc}
     */
    public function getEncryptKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEncryptKey', []);

        return parent::getEncryptKey();
    }

    /**
     * {@inheritDoc}
     */
    public function getBlockCipher()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBlockCipher', []);

        return parent::getBlockCipher();
    }

    /**
     * {@inheritDoc}
     */
    public function encrypt($encrypt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'encrypt', [$encrypt]);

        return parent::encrypt($encrypt);
    }

    /**
     * {@inheritDoc}
     */
    public function decrypt($decrypt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'decrypt', [$decrypt]);

        return parent::decrypt($decrypt);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', []);

        return parent::toArray();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', []);

        return parent::setCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', []);

        return parent::setUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

}
