<?php
$this->headLink()
    ->prependStylesheet($this->basePath('assets/plugins/bootstrap-table/css/bootstrap-table.min.css'))
?>
<div class="content-page">
    <div class="content">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-header-2">
                        <h4 class="page-title">Usuários</h4>
                        <ol class="breadcrumb">
                            <li>
                                <a href="<?= $this->url('home') ?>">Home</a>
                            </li>
                            <li class="active">
                                <span>Usuários</span>
                            </li>
                        </ol>
                    </div>
                </div>
            </div>
            <?= $this->partial('partials/loading.phtml'); ?>
            <div class="row page-content" style="display: none">
                <div class="col-sm-12">
                    <div class="card-box">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="fixed-table-toolbar">
                                    <div class="bs-bars pull-left">
                                        <a href="<?= $this->url('users/default', ['action' => 'new']) ?>" class="btn btn-primary">
                                            <i class="fa fa-plus m-r-5"></i>Novo
                                        </a>
                                    </div>
                                    <div class="columns columns-right btn-group pull-right">
                                        <div class="keep-open btn-group" title="Columns">
                                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                                <i class="fa fa-bars"></i>
                                                <span class="caret"></span>
                                            </button>
                                            <ul class="dropdown-menu" role="menu">
                                                <li>
                                                    <a href="javascript:void(0)">Imprimir Lista</a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="pull-right search">
                                        <input class="form-control" type="text" placeholder="Localizar">
                                    </div>
                                </div>
                                <div class="fixed-table-container">
                                    <div class="table-responsive">
                                        <table class="table table-striped table-hover m-t-10" id="table-users">
                                            <thead>
                                                <tr>
                                                    <td class="bs-checkbox ">
                                                        <input name="selectAll" type="checkbox">
                                                    </td>
                                                    <th>#</th>
                                                    <th>Nome</th>
                                                    <th>Email</th>
                                                    <th>Status</th>
                                                    <th class="text-center" style="width: 150px">Options</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <?= $this->partial('partials/users/users-table-tbody.phtml', ['data' => $this->data]) ?>
                                            </tbody>
                                        </table>
                                    </div>
                                    <div class="fixed-table-pagination">
                                        <?= $this->paginationControl($this->data, 'Sliding', 'partials/paginator', ['route' => 'users/paginator']) ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?= $this->partial('partials/footer.phtml'); ?>
</div>
<?php
$this->inlineScript()->captureStart();
echo <<<JS
    $(document).ready(function(){
        CheckboxAll.check('selectAll', '#table-users tbody');
    });
JS;
$this->inlineScript()->captureEnd();
?>
<?php
$this->inlineScript()
    ->prependFile($this->basePath('assets/pages/users/js/users.js'), 'text/javascript')
    ->prependFile($this->basePath('assets/js/checkbox-all.js'), 'text/javascript')
    ->prependFile($this->basePath('assets/js/modernizr.min.js'), 'text/javascript');
?>
<?= $this->partial('partials/flash_message.phtml', ['success' => $this->success, 'error' => $this->error]) ?>
