<?php

namespace Application\Service;

use Application\Entity\AbstractEntity;

class WarehousesService extends AbstractService
{
    protected $entity = \Application\Entity\Warehouses::class;

    public function create(Array $data): AbstractEntity
    {
        return parent::create($data); // TODO: Change the autogenerated stub
    }

    public function update(int $id, Array $data): AbstractEntity
    {
        return parent::update($id, $data); // TODO: Change the autogenerated stub
    }

   public function delete(Array $data): AbstractEntity
    {   
        $entity = $this->entityManager->getRepository($this->entity)->findOneBy($data);
        if ($entity) {
            $this->entityManager->getConnection()->beginTransaction();
            $this->getEventManager()->trigger('deleteWarehouse', $this, ['entity' => $entity]);
            $entity = parent::delete(['id' => $entity->getId() ]);
            $this->entityManager->getConnection()->commit();
        }
        return $entity;
    }
}