<div class="content-page">
    <div class="content">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-header-2">
                        <h4 class="page-title">Editar Produto</h4>
                        <ol class="breadcrumb">
                            <li>
                                <a href="<?= $this->url('home') ?>">Home</a>
                            </li>
                            <li>
                                <a href="<?= $this->url('products/default') ?>">Produtos</a>
                            </li>
                            <li class="active">Editar</li>
                        </ol>
                    </div>
                </div>
            </div>
            <?= $this->partial('partials/products/form.phtml'); ?>
        </div>
    </div>
    <?= $this->partial('partials/footer.phtml'); ?>
</div>
<?= $this->partial('partials/flash_message.phtml', ['success' => $this->success, 'error' => $this->error]) ?>