<?php
$this->headLink()
    ->prependStylesheet($this->basePath('assets/plugins/bootstrap-select/css/bootstrap-select.min.css'))
?>
<?= $this->partial('partials/loading.phtml'); ?>
<div class="content-page">
    <div class="content">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-header-2">
                        <h4 class="page-title">Checklist no Local de Armazenamento</h4>
                        <ol class="breadcrumb">
                            <li>
                                <a href="<?= $this->url('home') ?>">Home</a>
                            </li>
                            <li>
                                <a href="<?= $this->url('checklist/default') ?>">Checklist</a>
                            </li>
                            <li class="active">Editar</li>
                        </ol>
                    </div>
                </div>
            </div>

            <div class="row page-content" style="display: none">
                <div class="col-sm-12">
                    <div class="card-box">
                        <div class="row">
                            <form action="<?= $this->url("checklist/default", ["action" => "checked", "id" => $this->productCheck ]) ?>"
                                  class="form-horizontal" role="form" method="POST">
                                <input type="hidden" name="productCheck" value="<?= $this->productCheck ?>">
                                <?php
                                foreach ($this->quantity as $quantity):
                                    if (isset($quantity['id'])):
                                        ?>
                                        <input type="hidden" name="hidden[<?=$quantity['warehouse']->getId();?>]" value="<?= $quantity['id'] ?>">
                                        <?php
                                    endif;
                                    ?>
                                    <div class="form-group">
                                        <label class="col-md-4 control-label"><?= $quantity['warehouse']->getName(); ?></label>
                                        <div class="col-md-6">
                                            <input class="form-control"
                                                   name="name[<?= $quantity['warehouse']->getId(); ?>]"
                                                   value="<?= $quantity['quantity']; ?>"
                                                   type="number">
                                        </div>
                                    </div>
                                    <?php
                                endforeach;
                                ?>
                                <div class="col-sm-offset-4 col-sm-9">
                                    <button type="submit" class="btn btn-info waves-effect waves-light">Salvar</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?php
    $this->inlineScript()
        ->prependFile($this->basePath('assets/plugins/bootstrap-select/js/bootstrap-select.min.js'), 'text/javascript');
    ?>


