<?php
namespace Application\Repository;

/**
 * ProdutionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProdutionRepository extends \Doctrine\ORM\EntityRepository
{
}
