<?php

namespace Application\Repository;

/**
 * UnitsMeasureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitsMeasureRepository extends \Doctrine\ORM\EntityRepository
{
}
