<?php if ($this->data): ?>
    <?php /** @var $item \Application\Entity\Warehouses */ ?>
    <?php foreach ($this->data as $item): ?>
        <tr>
            <th><input class="checkbox" type="checkbox"></th>
            <th scope="row"><?= "{$item->getId()}" ?></th>
            <td><?= "{$item->getName()}" ?></td>
            <td><?= "{$this->getStatus($item->getActive())}" ?></td>
            <td class="text-right">
                <a href="<?= $this->url('warehouses/default', ['action' => 'edit', 'id' => $item->getId()]) ?>"
                   class="btn btn-primary btn-sm tooltips"
                   data-toggle="tooltip" data-placement="top"
                   title="<?= $this->translate('Edit') ?>">
                    <i class="fa fa-pencil"></i>
                </a>
                <button onclick="remove('<?= $item->getId() ?>')"
                        class="btn btn-danger btn-sm tooltips user-delete"
                        data-toggle="tooltip" data-placement="top"
                        title="<?= $this->translate('Delete') ?>">
                    <i class="fa fa-trash"></i>
                </button>
            </td>
        </tr>
    <?php endforeach; ?>
<?php endif; ?>