<div class="wrapper-page">
    <div class="card-box">
        <div class="panel-heading">
            <h3 class="text-center"> Maxim Gest<strong class="text-custom">o</strong>r</h3>
        </div>
        <div class="panel-body">
            <div class="alert alert-success">
                <p class="text-center"><?= $this->translate('Account Created Successfully') ?></p>
            </div>
            <p><?= $this->translate('Was sent a email to activation of the your account.') ?></p>
            <div class="row">
                <div class="col-md-12">
                    <form method="post">
                        <input class="btn btn-primary" type="submit" value="<?= $this->translate('Re-send email') ?>">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>