<div class="wrapper-page">
    <div class=" card-box">
        <div class="panel-heading">
            <div class="text-center">
                <p><?= sprintf($this->translate('Sign up and test the Maxim Gest%so%sr'), '<strong class="text-custom">', '</strong>') ?></p>
            </div>
        </div>

        <div class="panel-body">
            <?php /** @var $field \Zend\Form\Form */ ?>
            <?php $this->form->setAttribute('class', 'form-horizontal m-t-20'); ?>
            <?= $this->form()->openTag($this->form); ?>

            <div class="form-group">
                <div class="col-xs-12">

                </div>
            </div>

            <div class="form-group ">
                <div class="col-xs-12">
                    <div class="row">
                        <label class="col-md-12">Email</label>
                    </div>
                    <span><?= $this->user->getEmail() ?></span>
                </div>
            </div>

            <div class="form-group">
                <div class="col-xs-12">
                    <?php $field = $this->form->get('password'); ?>
                    <?php $field->setAttributes([
                        'class'       => 'form-control',
                        'placeholder' => $this->translate('Password'),
                    ]) ?>
                    <?= $this->formElement($field) ?>
                    <?= $this->formElementErrors($field) ?>
                </div>
            </div>

            <div class="form-group">
                <div class="col-xs-12">
                    <?php $field = $this->form->get('password-confirm'); ?>
                    <?php $field->setAttributes([
                        'class'       => 'form-control',
                        'placeholder' => $this->translate('Password Confirm'),
                    ]) ?>
                    <?= $this->formElement($field) ?>
                    <?= $this->formElementErrors($field) ?>
                </div>
            </div>

            <div class="form-group">
                <div class="col-xs-12">
                    <div class="checkbox checkbox-primary">
                        <input id="checkbox-signup" type="checkbox" checked="checked">
                        <label for="checkbox-signup"><?= sprintf($this->translate('I accept %s Terms and Conditions %s'), '<a href="#">', '</a>') ?></label>
                    </div>
                </div>
            </div>

            <div class="form-group text-center m-t-40">
                <div class="col-xs-12">
                    <?php $field = $this->form->get('submit'); ?>
                    <?php $field->setLabel($this->translate('Register')); ?>
                    <?php $field->setAttributes([
                        'type'  => 'submit',
                        'class' => 'btn btn-pink btn-block text-uppercase waves-effect waves-light',
                    ]) ?>
                    <?= $this->formElement($field) ?>
                </div>
            </div>

            <?= $this->form()->closeTag($this->form); ?>
        </div>
    </div>
</div>