<div class="wrapper-page">
    <div class="card-box">
        <div class="panel-heading">
            <h3 class="text-center"><strong class="text-custom">S</strong>anta <strong class="text-custom">M</strong>ania
            </h3>
        </div>
        <div class="panel-body">
            <form class="form-horizontal m-t-20" method="post" action="<?= $this->url('login') ?>">
                <?php if (count($this->error)): ?>
                    <div class="alert alert-danger">
                        <?php foreach ($this->error as $item) ; ?>
                        <p class="text-center"><?= $item; ?></p>
                    </div>
                <?php endif; ?>
                <?php if (count($this->success)): ?>
                    <div class="alert alert-success">
                        <?php foreach ($this->success as $item) ; ?>
                        <p class="text-center"><?= $item; ?></p>
                    </div>
                <?php endif; ?>
                <div class="form-group ">
                    <div class="col-xs-12">
                        <input name="email" class="form-control" type="text" required="" placeholder="E-mail">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-xs-12">
                        <input name="password" class="form-control" type="password" required="" placeholder="Senha">
                    </div>
                </div>
                <div class="form-group text-center m-t-40">
                    <div class="col-xs-12">
                        <button class="btn btn-pink btn-block text-uppercase waves-effect waves-light" type="submit">Acessar</button>
                    </div>
                </div>
                <div class="form-group m-t-20 m-b-0">
                    <div class="col-sm-12">
                        <a href="<?= $this->url('recover') ?>" class="text-dark"><i class="fa fa-lock m-r-5"></i> Esqueci senha</a>
                    </div>
                </div>
                <div class="form-group m-t-20 m-b-0"></div>
            </form>
        </div>
    </div>
</div>