<div class="wrapper-page">
    <div class="panel panel-default alt with-footer">
        <div class="panel-heading"><h2>Login Form</h2></div>
        <div class="panel-body">
            <form action="#" class="">
                <div class="form-group">
                    <div class="col-xs-12">
                        <p>Enter your email to reset your password</p>
                        <div class="input-group">
									<span class="input-group-addon">
										<i class="ion-android-unlock"></i>
									</span>
                            <input type="text" class="form-control" placeholder="Email Address">
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="panel-footer">
            <div class="clearfix">
                <a href="extras-login.html" class="btn btn-default-alt pull-left mb-n">Go Back</a>
                <a href="#" class="btn btn-primary pull-right">Reset</a>
            </div>
        </div>
    </div>
</div>