<div class="wrapper-page">
    <div class=" card-box">
        <div class="panel-heading">
            <div class="text-center">
                <p><?= sprintf($this->translate('Sign up and test the Maxim Gest%so%sr'), '<strong class="text-custom">', '</strong>') ?></p>
            </div>
        </div>

        <div class="panel-body">
            <?php /** @var $field \Zend\Form\Form */ ?>
            <?php $this->form->setAttribute('class', 'form-horizontal m-t-20'); ?>
            <?= $this->form()->openTag($this->form); ?>

            <div class="form-group">
                <div class="col-xs-12">
                    <?php $field = $this->form->get('name'); ?>
                    <?php $field->setAttributes([
                        'class'       => 'form-control',
                        'placeholder' => $this->translate('Name'),
                    ]) ?>
                    <?= $this->formElement($field) ?>
                    <?= $this->formElementErrors()
                        ->setMessageOpenFormat('<ul class="parsley-errors-list filled"><li class="parsley-required">')
                        ->setMessageSeparatorString('</li><li class="parsley-required">')
                        ->setMessageCloseString('</li></ul>')
                        ->render($field); ?>
                </div>
            </div>

            <div class="form-group ">
                <div class="col-xs-12">
                    <?php $field = $this->form->get('email'); ?>
                    <?php $field->setAttributes([
                        'class'       => 'form-control',
                        'placeholder' => $this->translate('E-mail'),
                    ]) ?>
                    <input type="email" name="email" style="display: none">
                    <?= $this->formElement($field) ?>
                    <?= $this->formElementErrors($field) ?>
                </div>
            </div>

            <div class="form-group">
                <div class="col-xs-12">
                    <?php $field = $this->form->get('password'); ?>
                    <?php $field->setAttributes([
                        'class'       => 'form-control',
                        'placeholder' => $this->translate('Password'),
                    ]) ?>
                    <?= $this->formElement($field) ?>
                    <?= $this->formElementErrors($field) ?>
                </div>
            </div>

            <div class="form-group">
                <div class="col-xs-12">
                    <?php $field = $this->form->get('password-confirm'); ?>
                    <?php $field->setAttributes([
                        'class'       => 'form-control',
                        'placeholder' => $this->translate('Password Confirm'),
                    ]) ?>
                    <?= $this->formElement($field) ?>
                    <?= $this->formElementErrors($field) ?>
                </div>
            </div>

            <div class="form-group">
                <div class="col-xs-12">
                    <div class="checkbox checkbox-primary">
                        <input id="checkbox-signup" type="checkbox" checked="checked">
                        <label for="checkbox-signup"><?= sprintf($this->translate('I accept %s Terms and Conditions %s'), '<a href="#">', '</a>') ?></label>
                    </div>
                </div>
            </div>

            <div class="form-group text-center m-t-40">
                <div class="col-xs-12">
                    <?php $field = $this->form->get('submit'); ?>
                    <?php $field->setLabel($this->translate('Register')); ?>
                    <?php $field->setAttributes([
                        'type'  => 'submit',
                        'class' => 'btn btn-pink btn-block text-uppercase waves-effect waves-light',
                    ]) ?>
                    <?= $this->formElement($field) ?>
                </div>
            </div>

            <div class="form-group m-t-20 m-b-0">
                <div class="col-sm-12 text-center">
                    <h4><b><?= $this->translate('Sign Up with') ?></b></h4>
                </div>
            </div>

            <div class="form-group m-b-0 text-center">
                <div class="col-sm-12">
                    <a href="<?= $this->url('register-facebook') ?>" type="button" class="btn btn-facebook waves-effect waves-light m-t-20">
                        <i class="fa fa-facebook m-r-5"></i> Facebook
                    </a>

                    <button type="button" class="btn btn-twitter waves-effect waves-light m-t-20">
                        <i class="fa fa-twitter m-r-5"></i> Twitter
                    </button>

                    <button type="button" class="btn btn-googleplus waves-effect waves-light m-t-20">
                        <i class="fa fa-google-plus m-r-5"></i> Google+
                    </button>
                </div>
            </div>
            <?= $this->form()->closeTag($this->form); ?>
        </div>
    </div>
</div>