<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="A fully featured admin theme which can be used to build CRM, CMS, etc.">
        <meta name="author" content="Maxim Web">

        <link rel="shortcut icon" href="https://maximweb.com.br/wp-content/uploads/2016/01/Logo-MW.png">

        <title>Santa Mania Checklist - Login</title>

        <link href="<?= $this->basePath('assets/css/bootstrap.min.css') ?>" rel="stylesheet" type="text/css"/>
        <link href="<?= $this->basePath('assets/css/core.css') ?>" rel="stylesheet" type="text/css"/>
        <link href="<?= $this->basePath('assets/css/components.css') ?>" rel="stylesheet" type="text/css"/>
        <link href="<?= $this->basePath('assets/css/icons.css') ?>" rel="stylesheet" type="text/css"/>
        <link href="<?= $this->basePath('assets/css/pages.css') ?>" rel="stylesheet" type="text/css"/>
        <link href="<?= $this->basePath('assets/css/responsive.css') ?>" rel="stylesheet" type="text/css"/>

        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->

        <script src="<?= $this->basePath('assets/js/modernizr.min.js') ?>"></script>
    </head>
    <body>
        <div class="account-pages"></div>
        <div class="clearfix"></div>
        <?= $this->content; ?>
        <script>
            var resizefunc = [];
        </script>
        <!-- jQuery  -->
        <script src="<?= $this->basePath('assets/js/jquery.min.js') ?>"></script>
        <script src="<?= $this->basePath('assets/js/bootstrap.min.js') ?>"></script>
        <script src="<?= $this->basePath('assets/js/detect.js') ?>"></script>
        <script src="<?= $this->basePath('assets/js/fastclick.js') ?>"></script>
        <script src="<?= $this->basePath('assets/js/jquery.slimscroll.js') ?>"></script>
        <script src="<?= $this->basePath('assets/js/jquery.blockUI.js') ?>"></script>
        <script src="<?= $this->basePath('assets/js/waves.js') ?>"></script>
        <script src="<?= $this->basePath('assets/js/wow.min.js') ?>"></script>
        <script src="<?= $this->basePath('assets/js/jquery.nicescroll.js') ?>"></script>
        <script src="<?= $this->basePath('assets/js/jquery.scrollTo.min.js') ?>"></script>
        <script src="<?= $this->basePath('assets/js/jquery.core.js') ?>"></script>
        <script src="<?= $this->basePath('assets/js/jquery.app.js') ?>"></script>
    </body>
</html>