<?php if ($this->data): ?>
    <?php /** @var $item \Application\Entity\ProductStatus */ ?>
    <?php foreach ($this->data as $item): ?>
        <tr>
            <th><input class="checkbox" type="checkbox"></th>
            <th scope="row"><?= "{$item->getId()}" ?></th>
            <td><?= "{$item->getName()}" ?></td>
            <td class="text-right">
                <a href="<?= $this->url('product-status/default', ['action' => 'view', 'code' => $item->getCode()]) ?>"
                   class="btn btn-default btn-sm tooltips"
                   data-toggle="tooltip" data-placement="top"
                   title="<?= $this->translate('Preview') ?>">
                    <i class="fa fa-folder"></i>
                </a>
                <a href="<?= $this->url('product-status/default', ['action' => 'edit', 'code' => $item->getCode()]) ?>"
                   class="btn btn-primary btn-sm tooltips"
                   data-toggle="tooltip" data-placement="top"
                   title="<?= $this->translate('Edit') ?>">
                    <i class="fa fa-pencil"></i>
                </a>
                <button onclick="remove('product-status', '<?= $item->getCode() ?>')"
                        class="btn btn-danger btn-sm tooltips user-delete"
                        data-toggle="tooltip" data-placement="top"
                        title="<?= $this->translate('Delete') ?>">
                    <i class="fa fa-trash"></i>
                </button>
            </td>
        </tr>
    <?php endforeach; ?>
<?php endif; ?>
<?= $this->partial('partials/delete.phtml'); ?>
