<div class="left side-menu">
    <div class="sidebar-inner slimscrollleft">
        <div id="sidebar-menu">
            <ul>
                <li class="text-muted menu-title"><?= "{$this->identity()->getFirstname()} {$this->identity()->getLastname()}" ?></li>
                <?php /** @var $page \Zend\Navigation\Page\Mvc */ ?>
                <?php foreach ($this->container as $page) {

                    $subPages      = $page->getPages();
                    $totalSubPages = count($subPages);

                    $arrow   = $totalSubPages ? '<span class="menu-arrow"></span>' : '';
                    $link    = $totalSubPages > 0 ? "javascript:void(0)" : "href='{$this->url($page->getRoute())}'";
                    $icon    = $page->get('icon') ? '<i class="' . $page->get('icon') . '"></i>' : '';
                    $liClass = $totalSubPages ? 'class="has_sub"' : '';

                    $route = $page->getRoute();

                    echo "<li $liClass><a $link> $icon <span>{$this->translate($page->getLabel())}</span> $arrow</a>";

                    if ($totalSubPages) {

                        echo '<ul class="list-unstyled">';
                        /** @var $subPage \Zend\Navigation\Page\Mvc */
                        foreach ($subPages as $subPage) {

                            //if ($this->getRoute() == $subPage->getRoute() || "{$this->getRoute()}/default" == $subPage->getRoute())
                            //    echo "<li><a href=\"javascript:void(0)\"> <span>{$this->translate($subPage->getLabel())}</span> </a></li>";
                            //else
                                echo "<li><a href=\"{$this->url($subPage->getRoute(), ['action' => $subPage->getAction()])}\"> <span>{$this->translate($subPage->getLabel())}</span> </a></li>";
                        }
                        echo '</ul>';
                    }
                    echo "</li>";
                } ?>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>