<?php
$urlPattern = $_SERVER['REQUEST_URI'];

$formatUrl = function ($page) use ($urlPattern) {

    if (!preg_match('/page/', $urlPattern)) {
        return $urlPattern . '/page/' . (int)$page;
    } else {
        return preg_replace('@/page/(\d+)@', '/page/' . (int)$page, $urlPattern);
    }
};
?>
<div class="row">
    <div class="col-sm-6">
        <div><?= sprintf($this->translate('Mostrando de %s até %s de %s registros'), $this->firstItemNumber, $this->lastItemNumber, $this->totalItemCount) ?>
        </div>
    </div>
    <?php if ($this->pageCount > 1): ?>
        <div class="col-md-6">
            <div class="text-right">
                <ul class="pagination pagination-sm">
                    <?php if (isset($this->first) && $this->first != $this->current): ?>
                        <li>
                            <a href="<?= $formatUrl($this->first) ?>"><i class="fa fa-angle-double-left"></i></a>
                        </li>
                    <?php endif; ?>
                    <?php if (isset($this->previous)): ?>
                        <li>
                            <a href="<?= $formatUrl($this->previous) ?>"><i class="fa fa-angle-left"></i></a>
                        </li>
                    <?php endif; ?>
                    <?php foreach ($this->pagesInRange as $page): ?>
                        <?php if ($page != $this->current): ?>
                            <li>
                                <a href="<?= $formatUrl($page); ?>"><?= $page; ?> </a>
                            </li>
                        <?php else: ?>
                            <li class="active">
                                <a href="#"><?= $page; ?> </a>
                            </li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                    <?php if (isset($this->next)): ?>
                        <li>
                            <a href="<?= $formatUrl($this->next); ?>"><i class="fa fa-angle-right"></i></a>
                        </li>
                    <?php endif; ?>
                    <?php if (isset($this->last) && $this->last != $this->current): ?>
                        <li>
                            <a href="<?= $formatUrl($this->last); ?>"><i class="fa fa-angle-double-right"></i></a>
                        </li>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
    <?php endif; ?>
</div>
