<div class="topbar">
    <div class="topbar-left">
        <div class="text-center">
            <a href="<?= $this->url('home'); ?>" class="logo">
                <i class="icon-c-logo">
                    <strong class="text-custom">S</strong><strong class="text-custom">M</strong>
                </i>
                <span><strong class="text-custom">S</strong>anta <strong class="text-custom">M</strong>ania</span>
            </a>
        </div>
    </div>
    <div class="navbar navbar-default" role="navigation">
        <div class="container">
            <div class="">
                <div class="pull-left">
                    <button class="button-menu-mobile open-left waves-effect waves-light">
                        <i class="md md-menu"></i>
                    </button>
                    <span class="clearfix"></span>
                </div>
                <ul class="nav navbar-nav navbar-right pull-right">
                    <li class="dropdown top-menu-item-xs">
                        <a class="dropdown-toggle waves-effect waves-light"><?= "{$this->identity()->getFirstname()} {$this->identity()->getLastname()}"; ?></a>
                    </li>
                    <li class="dropdown top-menu-item-xs">
                        <a href="#" class="dropdown-toggle profile waves-effect waves-light" data-toggle="dropdown" aria-expanded="true">
                            <img src="https://www.gravatar.com/avatar/<?= md5($this->identity()->getEmail()); ?>?s=29" alt="user-img" class="img-circle">
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="<?= $this->url('profile') ?>">
                                    <i class="ti-user m-r-10 text-custom"></i>
                                    Meus dados
                                </a>
                            </li>
                            <li>
                                <a href="javascript:void(0)"><i class="ti-settings m-r-10 text-custom"></i> Configurações</a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="<?= $this->url('logout') ?>"><i class="ti-power-off m-r-10 text-danger"></i> Sair</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>