<?php
$this->headLink()
    ->prependStylesheet($this->basePath('assets/plugins/bootstrap-select/css/bootstrap-select.min.css'))
?>
<?= $this->partial('partials/loading.phtml'); ?>
<div class="row page-content" style="display: none">
    <div class="col-sm-12">
        <div class="card-box">
            <div class="row">
                <div class="col-md-12">

                    <?php /** @var $field \Zend\Form\Form */ ?>
                    <?php $this->form->setAttribute('class', 'form-horizontal'); ?>
                    <?= $this->form()->openTag($this->form); ?>

                    <div class="form-group">
                        <?php $field = $this->form->get('name'); ?>
                        <?php $field->setAttribute('class', 'form-control'); ?>
                        <?php $field->setLabel('Nome'); ?>
                        <?php $field->setLabelAttributes(['class' => 'col-md-2 control-label']); ?>
                        <?= $this->formLabel($field); ?>
                        <div class="col-md-8">
                            <?= $this->formElement($field); ?>
                            <span class="help-block"><?= $this->formElementErrors($field) ?></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <?php $field = $this->form->get('product_category'); ?>
                        <?php $field->setAttributes([
                            'class'            => 'selectpicker',
                            'data-live-search' => 'true', 'data-style' => 'btn-white',
                        ]); ?>
                        <?php $field->setLabel('Categoria do Produto'); ?>
                        <?php $field->setLabelAttributes(['class' => 'col-md-2 control-label']); ?>
                        <?= $this->formLabel($field); ?>
                        <div class="col-md-8">
                            <div class="input-group">
                                <div class="input-group-btn">
                                    <?= $this->formElement($field); ?>
                                    <a class="btn btn-primary waves-effect waves-light" data-toggle="modal" data-target="#product-category-modal"><i class="glyphicon glyphicon-plus"></i></a>
                                </div>
                                <span class="help-block"><?= $this->formElementErrors($field) ?></span>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <?php $field = $this->form->get('units_measure'); ?>
                        <?php $field->setAttributes([
                            'class'            => 'selectpicker',
                            'data-live-search' => 'true', 'data-style' => 'btn-white',
                        ]); ?>
                        <?php $field->setLabel('Unidade de Medida'); ?>
                        <?php $field->setLabelAttributes(['class' => 'col-md-2 control-label']); ?>
                        <?= $this->formLabel($field); ?>
                        <div class="col-md-8">
                            <div class="input-group">
                                <div class="input-group-btn">
                                    <?= $this->formElement($field); ?>
                                    <a class="btn btn-primary waves-effect waves-light" data-toggle="modal" data-target="#units-measure-modal"><i class="glyphicon glyphicon-plus"></i></a>
                                </div>
                                <span class="help-block"><?= $this->formElementErrors($field) ?></span>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-8">
                            <div class="checkbox checkbox-primary">
                                <?php $field = $this->form->get('active'); ?>
                                <?php $field->setLabel('Ativo'); ?>
                                <?= $this->formElement($field); ?>
                                <?= $this->formLabel($field); ?>
                            </div>
                        </div>
                    </div>

                    <div class="form-group m-b-0">
                        <div class="col-sm-offset-2 col-sm-8">
                            <?php $field = $this->form->get('submit'); ?>
                            <?php $field->setAttributes([
                                'class' => 'btn btn-info waves-effect waves-light',
                            ]); ?>
                            <?php $field->setLabel('Salvar'); ?>
                            <?= $this->formButton($field); ?>
                        </div>
                    </div>

                    <?= $this->formHidden($this->form->get('id')) ?>
                    <?= $this->form()->closeTag($this->form); ?>
                </div>
            </div>
        </div>
    </div>
</div>
<?= $this->partial('partials/product-categories/modal.phtml'); ?>
<?= $this->partial('partials/units-measure/modal.phtml'); ?>
<?php
$this->inlineScript()
    ->prependFile($this->basePath('assets/plugins/bootstrap-select/js/bootstrap-select.min.js'), 'text/javascript');
?>

