<div class="content-page">
    <div class="content">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="btn-group pull-right m-t-15">
                        <button type="button" class="btn btn-default dropdown-toggle waves-effect waves-light" data-toggle="dropdown" aria-expanded="false">Settings
                            <span class="m-l-5"><i class="fa fa-cog"></i></span></button>
                        <ul class="dropdown-menu drop-menu-right" role="menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                        </ul>
                    </div>
                    <div class="page-header-2">
                        <h4 class="page-title">Blank Page</h4>
                        <ol class="breadcrumb">
                            <li>
                                <a href="<?= $this->url('home') ?>"><?= $this->translate('Home') ?></a>
                            </li>
                            <li>
                                <a href="#">Título</a>
                            </li>
                            <li class="active">
                                Lista
                            </li>
                        </ol>
                    </div>
                </div>
            </div>
            <?= $this->partial('partials/loading.phtml'); ?>
            <div class="row page-content" style="display: none">
                <div class="col-lg-12">
                </div>
            </div>
        </div>
    </div>
    <?= $this->partial('partials/footer.phtml'); ?>
</div>
<?php
$this->inlineScript()
//->prependFile($this->basePath('assets/accounts/accounts-tour.js'), 'text/javascript');
?>
<?= $this->partial('partials/flash_message.phtml', ['success' => $this->success, 'error' => $this->error]) ?>
